-- MySQL Script generated by MySQL Workbench
-- Mo 24 Okt 2016 15:50:24 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tuegutesdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tuegutesdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tuegutesdb` DEFAULT CHARACTER SET utf8 ;
USE `tuegutesdb` ;

-- -----------------------------------------------------
-- Table `tuegutesdb`.`Vertrauen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tuegutesdb`.`Vertrauen` ;

CREATE TABLE IF NOT EXISTS `tuegutesdb`.`Vertrauen` (
  `idVertrauen` INT NOT NULL,
  `Vertrauenslevelbezeichnung` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVertrauen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tuegutesdb`.`Benutzergruppe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tuegutesdb`.`Benutzergruppe` ;

CREATE TABLE IF NOT EXISTS `tuegutesdb`.`Benutzergruppe` (
  `idBenutzergruppe` INT NOT NULL,
  `Gruppenbezeichnung` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBenutzergruppe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tuegutesdb`.`Benutzer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tuegutesdb`.`Benutzer` ;

CREATE TABLE IF NOT EXISTS `tuegutesdb`.`Benutzer` (
  `idBenutzer` INT NOT NULL AUTO_INCREMENT,
  `Benutzername` VARCHAR(48) NOT NULL,
  `Passwort` VARCHAR(32) NOT NULL,
  `Email` VARCHAR(128) NOT NULL,
  `RegDatum` DATETIME NOT NULL,
  `Punkte` INT NOT NULL,
  `idVertrauen` INT NOT NULL,
  `idBenutzergruppe` INT NOT NULL,
  `Status` ENUM('nichtVerifiziert', 'Verfiziert') NOT NULL,
  PRIMARY KEY (`idBenutzer`),
  UNIQUE INDEX `idBenutzer_UNIQUE` (`idBenutzer` ASC),
  UNIQUE INDEX `Benutzername_UNIQUE` (`Benutzername` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  INDEX `fk_Benutzer_Vertrauen1_idx` (`idVertrauen` ASC),
  INDEX `fk_Benutzer_Benutzergruppe1_idx` (`idBenutzergruppe` ASC),
  CONSTRAINT `fk_Benutzer_Vertrauen1`
    FOREIGN KEY (`idVertrauen`)
    REFERENCES `tuegutesdb`.`Vertrauen` (`idVertrauen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Benutzer_Benutzergruppe1`
    FOREIGN KEY (`idBenutzergruppe`)
    REFERENCES `tuegutesdb`.`Benutzergruppe` (`idBenutzergruppe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tuegutesdb`.`Datenschutz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tuegutesdb`.`Datenschutz` ;

CREATE TABLE IF NOT EXISTS `tuegutesdb`.`Datenschutz` (
  `idDatenschutz` INT NOT NULL,
  `Datenschutzkey` VARCHAR(64) NOT NULL,
  `cryptkey` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`idDatenschutz`),
  CONSTRAINT `fk_Datenschutz_Benutzer1`
    FOREIGN KEY (`idDatenschutz`)
    REFERENCES `tuegutesdb`.`Benutzer` (`idBenutzer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tuegutesdb`.`PLZ`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tuegutesdb`.`PLZ` ;

CREATE TABLE IF NOT EXISTS `tuegutesdb`.`PLZ` (
  `PLZ` INT NOT NULL,
  `Ort` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`PLZ`, `Ort`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tuegutesdb`.`persData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tuegutesdb`.`persData` ;

CREATE TABLE IF NOT EXISTS `tuegutesdb`.`persData` (
  `idpersData` INT NOT NULL,
  `Vorname` VARCHAR(64) NOT NULL,
  `Nachname` VARCHAR(64) NOT NULL,
  `Geschlecht` VARCHAR(1) NOT NULL,
  `Strasse` VARCHAR(128) NULL,
  `Hausnummer` VARCHAR(5) NULL,
  `PLZ` INT NULL,
  `Telefonnummer` VARCHAR(20) NULL,
  `Messengernummer` VARCHAR(20) NULL,
  `Geburtsdatum` DATE NOT NULL,
  PRIMARY KEY (`idpersData`),
  INDEX `PLZ` (`PLZ` ASC),
  CONSTRAINT `fk_persData_PLZ1`
    FOREIGN KEY (`PLZ`)
    REFERENCES `tuegutesdb`.`PLZ` (`PLZ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persData_Benutzer1`
    FOREIGN KEY (`idpersData`)
    REFERENCES `tuegutesdb`.`Benutzer` (`idBenutzer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tuegutesdb`.`Texte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tuegutesdb`.`Texte` ;

CREATE TABLE IF NOT EXISTS `tuegutesdb`.`Texte` (
  `idTexte` INT NOT NULL,
  `Avatar` TEXT(65535) NULL,
  `Hobbies` TINYTEXT NULL,
  `Beschreibung` TEXT(2000) NULL,
  PRIMARY KEY (`idTexte`),
  CONSTRAINT `fk_Texte_Benutzer1`
    FOREIGN KEY (`idTexte`)
    REFERENCES `tuegutesdb`.`Benutzer` (`idBenutzer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tuegutesdb`.`Taten`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tuegutesdb`.`Taten` ;

CREATE TABLE IF NOT EXISTS `tuegutesdb`.`Taten` (
  `idGuteTat` INT NOT NULL AUTO_INCREMENT,
  `Bezeichnung` VARCHAR(64) NULL,
  `Kontaktperson` INT NOT NULL,
  `Kategorie` VARCHAR(64) NOT NULL,
  `Strasse` VARCHAR(128) NULL,
  `Hausnummer` VARCHAR(5) NULL,
  `PLZ` INT NOT NULL,
  `Zeitpunkt` DATETIME NULL,
  `Organisation` VARCHAR(128) NULL,
  `Anzahl Helfer` INT NULL,
  `idVertrauen` INT NOT NULL,
  `Status` ENUM('a', 'b', 'c') NOT NULL,
  PRIMARY KEY (`idGuteTat`, `Kontaktperson`),
  INDEX `fk_Taten_PLZ1_idx` (`PLZ` ASC),
  INDEX `fk_Taten_Vertrauen1_idx` (`idVertrauen` ASC),
  INDEX `fk_Taten_Benutzer1_idx` (`Kontaktperson` ASC),
  CONSTRAINT `fk_Taten_PLZ1`
    FOREIGN KEY (`PLZ`)
    REFERENCES `tuegutesdb`.`PLZ` (`PLZ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Taten_Vertrauen1`
    FOREIGN KEY (`idVertrauen`)
    REFERENCES `tuegutesdb`.`Vertrauen` (`idVertrauen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Taten_Benutzer1`
    FOREIGN KEY (`Kontaktperson`)
    REFERENCES `tuegutesdb`.`Benutzer` (`idBenutzer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tuegutesdb`.`Tatentext`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tuegutesdb`.`Tatentext` ;

CREATE TABLE IF NOT EXISTS `tuegutesdb`.`Tatentext` (
  `idTatentext` INT NOT NULL,
  `Beschreibung` TEXT(2000) NULL,
  `Bilder` TEXT(65535) NULL,
  PRIMARY KEY (`idTatentext`),
  CONSTRAINT `fk_Tatentext_Taten1`
    FOREIGN KEY (`idTatentext`)
    REFERENCES `tuegutesdb`.`Taten` (`idGuteTat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
